#!/bin/bash

echo "*** division in static ***"
div(){
a=10
b=10
c=$((a/b))
echo "division of $a and $b : $c"
}
div

echo "---------------------------"

echo "*** division in dynamic ***"

echo "enter value of d"
read d
echo "enter value of e"
read e
div(){
f=$((d/e))
echo "division of $d and $e : $f"
}
div

