#!/bin/bash

echo "*** multiplication in static ***"
mul(){
a=10
b=10
c=$((a*b))
echo "multiplication of $a and $b : $c"
}
mul

echo "---------------------------------"

echo "*** multiplication in dynamic ***"

echo "enter value of d"
read d
echo "enter value of e"
read e
mul(){
f=$((d*e))
echo "multiplication of $d and $e : $f"
}
mul
